<a href="https://colab.research.google.com/github/amitvaghela19/Amit_Vaghela_Data_Analyst/blob/main/March_11_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# March 11,2026

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print("Hello World")

Hello World

In [ ]:
2+2

4

In [ ]:
x=3
y=4
if x>y:
  print("X is greater than Y")
else:
  print("Y is greater than X")

Y is greater than X

In [ ]:
x= int(input("Enter a number"))
y= int(input("Enter a number"))
if x>y:
  print(x,"is bigger number")
else:
  print(y," is bigger number")

KeyboardInterrupt: Interrupted by user

In [ ]:
# write a python program to store your name in a variable and print it.

x= "amit"
y= "Vasu"
z= "Aashish"
a= (x + y+ z)
print (x,y,z)
print(x + y + z)

x = 10
y = 20
print(x+y)

In [ ]:
x = 2
y = 4
print(x+y)

In [ ]:
#Write a program to store three numbers and print their average

x= 10
y= 20
z= 30
(x+y+z)/3

In [ ]:
x=7
y=3
x+y

In [ ]:

a = 5
a = 8
print (a)

In [ ]:
x = 3
y = 7

temp = x
x = y
y = temp

print(x, y)

In [ ]:
#Write a Python program to calculate the area of a rectangle using variables.
# Variables for length and width
length = 10
width = 5
area = length * width
print("The area of the rectangle is:", area)

In [ ]:
#Write a Python program to store two numbers and print the larger number.
x= int(input("Enter a number "))
y= int(input("Enter a number "))
if x>y:
  print(x,"is bigger number")
else:
  print(y," is bigger number")

In [ ]:
#Write a Python program to store first name and last name in variables and print the full name.

first_name = input("enter your first name ")
last_name = input("enter your last name ")
full_name = (first_name + " " + last_name).title()
print(full_name)

In [ ]:
print(3)

In [ ]:
x =65
z= str(65)
print(type(z))

In [ ]:
"""
           To print string and integer together,
           there are the following methods
           which can be useful
                                                         """

In [ ]:
name = "amit"
age = 25
print("my name is " + name + " and my age is " + str(age))       #by defining age as a string

In [ ]:
name = 'rahul'
age = '43'    #using quation mark to convert into string
print('my name is',name,'. my age is',age)

In [ ]:
name = 'mohit'
age= 22
print(f'my name is {name} and my age is {age}')        #using f statement

In [ ]:
#Write a Python program to store two numbers in variables and print their sum.

a= 10
b= 20
a+b

In [ ]:
#Write a program to store three numbers and print their average

x= 10
y= 20
z= 30
a = (x+y+z)/3
print(a)

In [ ]:
#Write a program to store three numbers and print their average
x= 10
y= 20
z= 30
a= np.average([x,y,z])                         #using numpy
print(a)

# March 12, 2026, live session

In [ ]:
#Write a Python program to print your name, age, and city in a single line.

x= ('amit,23, Brampton')
print (x)

In [ ]:
a = {                                                           #option 2
     "name": "amit",
     "age" : 27,
     "city": "Brampton"
}
print (a)

In [ ]:
name = "amit"                                                     #option 3
age = 26
city = "brampton"

print (f"my name is {name}, my age is {age} and my city is {city}")

In [ ]:
a = ["Amit",26,"Brampton"]                                  #option 4
print (a)

In [ ]:
# Write a program to take age as input and print the age after 5 years.

age= int(input("enter your age "))

age= age + 5
print(f"{age} is the age after 5 years")

In [ ]:
#Write a program to calculate the area of a rectangle.

a= int(input("enter the length "))
b= int(input("enter the width "))
area= a*b
print(f"area of rectangle is { area }")

In [ ]:
#Write a program to find the largest of two numbers.

a = int(input("enter the first number "))
b= int(input("enter the second number "))

if a > b :
  print(f"{a} is bigger than {b}")

else:
  print(f"{b} is bigger than {a}")

In [ ]:
#Write a program to print the length of a string
name = input("Enter your name ")
print (f"lenght of the name is {(len(name))}")

In [ ]:
#Write a program to count the number of digits in a number.

num = float(input("enter number "))
num = round(num) # Round to nearest integer for processing whole number digits
print(len(str(num)))

In [ ]:
#Write a program to sum the number of digits in a number.

num = float(input("enter number "))
num = round(num) # Round to nearest integer for processing whole number digits


# Convert the integer to a string, then iterate through each character, convert to int, and sum
sum_num = sum(int(digit) for digit in str(abs(int(num)))) #used abs function to convert negative value to poitive
print("sum of digits are ", sum_num)
 #acceture # genture

In [ ]:
#another way to solve it

num = float(input("enter a float number: "))
rounded_num = round(num)
num_str = str(abs(rounded_num))
sum_digits = 0
for digit in num_str:
    sum_digits += int(digit)

print("Rounded number:", rounded_num)
print("Sum of digits:", sum_digits)

# March 12, 2026, Homework

**python_beginner_excercise_variables_string**

**Python Practice Exercises**

Focus areas: Python variables, single-line variables, multi-line variables, and strings.

In [ ]:
# 1. Create a variable called name and assign your name to it. Print the value.
name = "amit"
print(name)

In [ ]:
# 2. Create two variables: age and city. Assign values and print them in one sentence.
age = int(input("enter your age "))
city = input("enter your city ")
print(f"My age is {age} and my city is {city}")

In [ ]:
# 3. Create three variables in a single line: a, b, and c. Assign numbers and print their sum.
(a,b,c)=(round(float(input( ) )),round(float(input( ) ) ),round(float(input( ) )))
d= a+b+c
print(f"Sum of a,b,c is : {d}")

In [ ]:
# 4. Create multiple variables in a single line with the same value (example: x = y = z). Print them.

x=y=z= 5
print(x, y, z)

In [ ]:
# 5. Swap two variables (a and b) without using a third variable and print the result.


i=0
for i in (0,2):
  (a,b)=(input(" " ),input(" " ))                                                # want to display numbers and name
  (a,b)=(b,a)
  print(f"your Swapped variables are {a +" "+ b}")
  i+= 1

In [ ]:
# 6. Write a program that stores your first name and last name in two variables and prints the full name.
first_name= input("First Name: ")
last_name= input("Last Name: ")
full_name= (first_name +" "+ last_name).title()                                  # output of (first_name + last_name).title() visually incorrect
print(full_name)                                                                 # as last_name is not getting the effect of title() function.

In [ ]:
# 7. Create variables length and width. Calculate and print the area of a rectangle.
a= abs(float(input("enter the length in Meter ")))
b= abs(float(input("enter the width in Meter ")))
area= a*b
print(f"Area of rectangle is {round(area, 2)} Meter")

In [ ]:
# 8. Store three subject marks in three variables and print the average.
import numpy as np

(Maths, Science, English) = (
    round(float(input("Maths: "))),
    round(float(input("Science: "))),
    round(float(input("English: ")))
)

avg_marks = np.average([Maths, Science, English])
print(f"Average of 3 Subjects are : {round(avg_marks, 2)}/100")

if avg_marks >= 90:
    print("Grade: A")
elif avg_marks >= 80:
  print("Grade: B")
elif avg_marks >= 60:
  print("Grade: C")
elif avg_marks >= 40:
  print("Grade: D")
else:
  print("Grade: F")

In [ ]:
# 9. Write a program to create a multi-line string that contains your address and print it.

address= """ 111 Airport RD,
 Brampton,
 Ontario,
 Canada"""
print(address)

#option 2

address= '\n 111 Airport RD,\n Brampton,\n Ontario,\n Canada'
print(address)

In [ ]:
#10. Store a quote in a string variable and print it.
x = input("Enter a quote: ").title()
print(x)

In [ ]:
# 11. Create a string variable called message. Print the length of the string.
message = input("Enter a message: ")
print(len(message))

In [ ]:
# 12. Write a program that converts a string 'hello world' to uppercase.

x= 'hello world'
print (x.upper())

In [ ]:
# 13. Write a program that converts the string 'PYTHON PROGRAMMING' to lowercase.
x= 'PYTHON PROGRAMMING'
print(x.lower())

In [ ]:
# 14. Create a string variable and print the first character and the last character.
x= input("Enter your variable: ")
print(x[0],x[-1])

In [ ]:
# 15. Write a program that joins two string variables using a space in between.
x= input("Enter your first variable: ").title()
y= input("Enter your second variable: ").title()
print(x+" "+y)

In [ ]:
# 16. Create a variable with a sentence and count how many characters are in it.
message = input("Enter a message: ")
print(len(message))

In [ ]:
# 17. Write a program that repeats a string 3 times using a variable.

x= input("Enter your variable: \n")   #x is defined outside of the loop because we need to print the same item 3 times (example: amit,amit,amit)
i=0                                   # if x is defined inside the loop it will ask input 3 times. (example: amit, aman, ajay)
for i in (0,3):
  print(x)
  i+=1

In [ ]:
# 18. Create a string variable and print it using both single quotes and double quotes.
a= 'alpha'
b= "beta"
print(a,b)

In [ ]:
# 19. Write a program that stores multiple lines using triple quotes and prints them.
address= """ 111 Airport RD,
 Brampton,
 Ontario,
 Canada"""
print(address)

In [ ]:
# 20. Create variables for product name and price, then print a sentence like: 'The price of Laptop is 50000.'
product_name = input("Enter product name: ")
price = input("Enter product price: ")
print(f'The price of {product_name} is {price}.')

# March 13, 2026, live session

In [ ]:
a = [2] * 5
print(a)

In [ ]:
b = [3]* 7
print (b)

In [ ]:
# important question                      -1 will be convert as 5 as a position so outcome is (x[5:3]) so it will give me null value but not give any error
x=[1,2,3,4,5]
print (x[-1:3])

In [ ]:
# updating the element

a = ['mango',4,"ashish"]
a[1]='carrot'
print(a)
a.remove('mango')
print(a)

In [ ]:
b=a.pop(1)
print(b)

# March 13, 2026, Homework

**Python Practice Questions -13-3-2026**

Topics Covered: Python Data Types, Lists, List Methods, Tuples, and Sets.

Instructions: Write Python programs to solve the following problems.






---


*Python Data Types*

In [ ]:
# 1. Create variables of different data types: int, float, string, and boolean. Print each variable and its data type.

x=4
print(type(x))
y=4.5
print(type(y))
z='amit'
print(type(z))
a=True
print(type(a))

In [ ]:
# 2. Write a program that converts an integer to a float and prints both values.
a= int(input("Enter Integer Number: "))
b= float(a)
print(a,b)

In [ ]:
# 3. Create a variable storing your name and age. Print a sentence using these variables.
name= input("Enter your name: ").title()
age= int(input("Enter your age: "))
print(f"My name is {name} and my age is {age}")

In [ ]:
# 4. Write a program that checks the type of a variable using the type() function.
x= input("Enter your variable: ")
print(type(x))                                   #Note: Python does not automatically convert input into boolean.
                                                 # Input: True then Output: class str

In [ ]:
# 5. Create variables for a number and a decimal value. Add them together and print the result.
x= int(input("Enter a number: "))
y= float(input("Enter a decimal value: "))
z= x+y
print(z)

*Python Lists*

In [ ]:
# 6. Create a list of five numbers and print the list.

lst = [1,2,3,4,5]
print(lst)

In [ ]:
# 7. Write a program to print the first and last elements of a list.
lst = [1,2,3,4,5]
print(lst[0],lst[-1])

In [ ]:
# 8. Create a list of fruits and print each fruit using a loop.
fruits = ['apple','mango','cherry','banana','grapes']
for x in fruits:
  print(x)

In [ ]:
# 9. Write a program to find the length of a list using len().       # True : Class Boolean
lst = [1,2,3,4,5,'amit','vijay','john','jane','joe',True]            # true : class str
print(len(lst))

In [ ]:
#10. Create a list of numbers and print the sum of all elements.
lst = [1,2,3,4,5]
print(sum(lst))

List Methods (append, remove, pop, del)

In [ ]:
# 11. Create a list of numbers and use append() to add a new number to the list.
a= [10,20,30,40,50]
a.append(100)
print(a)

In [ ]:
# 12. Create a list of fruits and remove one fruit using remove().
fruits = ['apple','mango','cherry','banana','grapes']
fruits.remove('mango')
print(fruits)

In [ ]:
# 13. Create a list of numbers and remove the last element using pop().
a= [10,20,30,40,50]
a.pop()
a.pop(0)
print(a)

In [ ]:
# 14. Create a list and delete the second element using del.
x = [1,2,3,'apple','cherry','john']
del x[1]
print(x)

In [ ]:
# 15. Write a program that adds three elements to a list using append() and prints the final list.
a= [10,20,30,40,50]
a.append(100)                          #option 1
a.append(200)
a.append(300)
print(a)

In [ ]:
a= [10,20,30,40,50]                         #option 2
for i in range(0,3):                        # I put print(a) inside the loop as a comment because I just want to show final list as an output.
  a.append(input())
  #print(a)
  i += 1
print(f"This is your final list {a}")

Tuple

In [ ]:

# 16. Create a tuple with five numbers and print it.
a= (1,2,3,4,5)
print(a)

In [ ]:
# 17. Write a program to print the first and last elements of a tuple.
a= (1,2,3,4,5)
print(a[0],a[-1])

In [ ]:
# 18. Create a tuple with three values and print its length.
a= (1,2,3)
print(len(a))

In [ ]:
# 19. Write a program to check whether an element exists in a tuple.
a= (1,2,3,4,5)
print(3 in a)

In [ ]:
# 20. Convert a tuple into a list and print the result.
a= (1,2,3,'apple','banana')
print (type(a))
b= list (a)
print (type(b))

Set

In [ ]:

# 21. Create a set of numbers and print the set.
a= {1,2,3,4,5,6,7}
print(a,type(a))

In [ ]:
# 22. Write a program to add a new element to a set using add().
a = {1,2,3,4,5}
a.add('john')
print(a)

In [ ]:
# 23. Create two sets and print their union.
a = {1,2,3,4,5}
b = {'apple','mango','banana'}
c = a.union(b)
print(c)

In [ ]:
# 24. Create two sets and print their intersection.
a = {1,2,3,4,5}
b = {10,30,50,70,90}
c= a.intersection(b)          ##Intersection returns only the common elements between two sets.
print(c)                      #If two sets have no elements in common, the intersection is an empty set: set().

In [ ]:
# 24. Create two sets and print their intersection.
a = {1,2,3,4,5}
b = {2,4,6,8,10}
c= a.intersection(b)
print(c)

In [ ]:
# 25. Write a program to remove an element from a set using remove().
a = {'apple','cherry',1,2,3}
a.remove('apple')
print (a)

# March 16, 2026, Live session

In [ ]:
#LIst


# 15. Write a program that adds three elements to a list using append() and prints the final list.
a= [10,20,30,40,50]
a.append(60)
a.append(70)
a.append(80)
print(a)

In [ ]:
a=[1,2,3,4,5,6]
a.append(50,60,70)        #cannot use use multiple items in append.
print(a)

In [ ]:
a= [10,20,30,40,50]                         #option 2
for i in range(0,3):                        # I put print(a) inside the loop as a comment because I just want to show final list as an output.
  a.append(input())
  #print(a)
  i += 1
print(f"This is your final list {a}")

# March 16, 2026, 65 questions

In [ ]:
#write a programme that store name and age  This is version-1
list_name=['amit','james']
list_age=[23,25]
list_age+list_name

In [ ]:
#This is version-2  [ In this version only 1 input per list is taken. So expected output is like ['John',31]
lst_name=[]
lst_age=[]
lst_name.append(input(' Enter your name').title().strip())
lst_age.append(int(input(' Enter your age')))
lst_name_age= (lst_name)+(lst_age)
print(lst_name_age)

In [ ]:
""" This is Version-3 [ In this version, 5 input per list.][change the while condition and can be adjusted as per needed].
stops after 5 input automatic."""

i=1
total = {}
while i !=6:

    name=input(' Enter your name').title()
    age=int(input(' Enter your age'))

    total[name]= age #stores name as key and age as value.
    print("Name:",name,"Age:",age)
    i=i+1
print("Summary",total)

#learned placement of syntax makes all the impact.
#Summary is printed in one line only not as a list.

# March, 18,2026, Calculator

In [ ]:
import math

print("----- Calculator -----")
print("Choose an operation:")
print("add, sub, mul, div, square, sqrt, log")
print("------------------------------------")

operation = input("Enter operation: ").lower()

# Addition
if operation == "add":
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    print("Result:", a + b)

# Subtraction
elif operation == "sub":
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    print("Result:", a - b)

# Multiplication
elif operation == "mul":
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    print("Result:", a * b)

# Division
elif operation == "div":
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    if b == 0:
        print("Error: Cannot divide by zero.")
    else:
        print("Result:", a / b)

# Square
elif operation == "square":
    a = float(input("Enter number: "))
    print("Result:", a ** 2)

# Square root
elif operation == "sqrt":
    a = float(input("Enter number: "))
    if a < 0:
        print("Error: Cannot take square root of a negative number.")
    else:
        print("Result:", math.sqrt(a))

# Log base 10
elif operation == "log10":
    a = float(input("Enter number: "))
    if a <= 0:
        print("Error: Log undefined for zero or negative numbers.")
    else:
        print("Result:", math.log10(a))

else:
    print("Invalid operation. Please choose a valid option.")

# March 19,2026

In [ ]:
"""



"""

# March 20,2026, Weekend Assignment

In [ ]:
# 1. Given a list [1, 2, 3], append the value 4 and print the updated list.


x = [1, 2, 3]
x.append(4)
print (x)

In [ ]:
#2. Insert the value 10 at index position 1 in the list [1, 2, 3]. Print the result.

x= [1,2,3]
x.insert(1,10)
print(x)

In [ ]:
#3. Remove the element 2 from the list [1, 2, 3] and print the list.
x = [1,2,3]
x.remove(2)
print(x)

In [ ]:
#4. From the list [1, 2, 3], remove the last element using an appropriate method and print that element.
x= [1,2,3]
x.pop()
print(x)

In [ ]:
#5. Reverse the list [1, 2, 3] and print the reversed list.
x= [1,2,3]
x.reverse()
print(x)

In [ ]:
#6. Assign one list to another variable and modify the second list. Observe and print the first list.
x= [1,2,3]
y= x
y.append(4)
print(x)

In [ ]:
#7. Create a copy of a list using slicing, modify the copied list, and print the original list.
x= [1,2,3]
y= x[:]
y.append(4)
print(x)

In [ ]:
#8. From the list [1, 2, 3, 4], print elements from index 1 to 2.
nums = [1, 2, 3, 4]
print(nums[1:3])

In [ ]:
#9. Multiply the list [1, 2, 3] by 2 and print the result.
x = [1,2,3]
y= x * 2
print(y)

In [ ]:
#10. Find and print the length of the list [1, 2, 3].
x= [1,2,3]
print(len(x),type(x))

In [ ]:
#11. Extend the list [1, 2, 3] by adding [4, 5] and print the result.
x= [1,2,3]
x.extend([4,5])
print(x)

In [ ]:
#12. Sort the list [3, 1, 2] in ascending order and print it.
x = [3,2,1]
x.reverse()
print(x)

# option 2

y= [3,2,1]
y.sort()
print(y)

In [ ]:
#13. Check whether 2 exists in the list [1, 2, 3] and print the result.
x= [1,2,3]
if 2 in x:
  print("2 exists in the list")
else:
  print("2 does not exist in the list")

In [ ]:
#14. Find the index of element 3 in the list [1, 2, 3].
x= [1,2,3]
print(x.index(3))

In [ ]:
#15. Count how many times 2 appears in [1, 2, 2, 3].
x=[1,2,2,3]
print(x.count(2))

In [ ]:
#16. Access and print the first element of the tuple (1, 2, 3).
x= (1,2,3)
print(x[0])

In [ ]:
#17. Access and print the last element of the tuple (1, 2, 3).
x=(1,2,3)
print(x[-1])

In [ ]:
#18. Add a new element 4 to the tuple (1, 2, 3) and print the result.
x=(1,2,3)
y= list(x)
y.append(4)
x= tuple(y)
print(x)

In [ ]:
#19. Find and print the length of the tuple (1, 2, 3).
x=(1,2,3)
print(len(x))

In [ ]:
#20. Check whether 2 exists in the tuple (1, 2, 3).
x=(1,2,3)
if 2 in x:
  print("2 exists in the tuple")

In [ ]:
#21. Print elements from index 1 to 2 in the tuple (1, 2, 3, 4).
x=(1,2,3,4)
print(x[1:3])

In [ ]:
#22. Multiply the tuple (1, 2, 3) by 2 and print the result.
x=(1,2,3)
y= x * 2
print(y)

In [ ]:
#23. Create a tuple with a single element 1 and print its type.
x=(1,)
print(type(x))

In [ ]:
#24. Find the index of element 2 in the tuple (1, 2, 3).
x=(1,2,3)
print(x.index(2))

In [ ]:
#25. Count how many times 2 appears in (1, 2, 2, 3).
x=(1,2,2,3)
print(x.count(2))

In [ ]:
#26. Create a set {1, 2, 3} and print it.
x={1,2,3}
print(x)

In [ ]:
#27. Create a set with duplicate values {1, 2, 2, 3} and print the result.
x={1,2,2,3}
print(x)

In [ ]:
#28. Add element 4 to the set {1, 2, 3} and print it.
x={1,2,3}
x.add(4)
print(x)

In [ ]:
#29. Remove element 2 from the set {1, 2, 3} and print it.
x={1,2,3}
x.remove(2)
print(x)

In [ ]:
#30. Check whether 2 exists in the set {1, 2, 3}.
x={1,2,3}
if 2 in x:
  print("2 exists in the set")

In [ ]:
#31. Find the union of sets {1, 2} and {2, 3}.
x={1,2}
y={2,3}
print(x.union(y))

In [ ]:
#32. Find the intersection of sets {1, 2} and {2, 3}.
x={1,2}
y={2,3}
print(x.intersection(y))

In [ ]:
#33. Find the difference between sets {1, 2, 3} and {2}.
x={1,2,3}
y={2}
print(x.difference(y))

In [ ]:
#34. Check whether {1, 2} is a subset of {1, 2, 3}.
x={1,2}
y={1,2,3}
print(x.issubset(y))

In [ ]:
#35. Check whether {1, 2, 3} is a superset of {2, 3}.
x={1,2,3}
y={2,3}
print(x.issuperset(y))

In [ ]:
#36. Access and print the value associated with key "a" in {"a":1, "b":2}.
x={"a":1, "b":2}
print(x["a"])

In [ ]:
#37. Add a new key-value pair "b":2 to the dictionary {"a":1}.
x={"a":1}
x["b"]=2
print(x)

In [ ]:
#38. Try to access a non-existing key "c" using a safe method and print the result.
x={"a":1}
print(x.get("c"))

In [ ]:
#39. Find and print the number of key-value pairs in {"a":1, "b":2}.
x={"a":1, "b":2}
print(len(x))

In [ ]:
#40. Print all keys of the dictionary {"a":1, "b":2}.
x={"a":1, "b":2}
print(x.keys())

In [ ]:
#41. Print all values of the dictionary {"a":1, "b":2}.
x={"a":1, "b":2}
print(x.values())

In [ ]:
#42. Print all key-value pairs as tuples from the dictionary.
x={"a":1, "b":2}
print(x.items())

In [ ]:
#43. Update the dictionary {"a":1} with a new key "b":2.
x={"a":1}
x["b"]=2
print(x)

In [ ]:
#44. Remove the key "a" from {"a":1, "b":2} and print the dictionary.
x={"a":1, "b":2}
x.pop("a")
print(x)

In [ ]:
#45. Check whether key "a" exists in the dictionary.
x={"a":1, "b":2}
if "a" in x:
  print("a exists in the dictionary")

In [ ]:
#46. Check whether key "c" does not exist in the dictionary.
x={"a":1, "b":2}
if "c" not in x:
  print("c does not exist in the dictionary")

In [ ]:
#47. Insert key "b" with value 2 using a default-setting method and print the returned value.
x={"a":1}
print(x.setdefault("b",2))

In [ ]:
#48. Use the same method on an existing key "a" and observe the result.
x={"a":1}
print(x.setdefault("a",2))

In [ ]:
#49. Create a dictionary using keyword arguments and print it.
x= dict(a=1,b=2)
print(x)

In [ ]:
#50. Create an empty dictionary, insert "a":1, and print it.
x={}
x["a"]=1
print(x)

In [ ]:
#51. Given a number 5, check if it is greater than 3 and print "A" if true.
num =5
if num > 3:
  print("A")

In [ ]:
#52. Given a number 2, print "A" if it is greater than 3, otherwise print "B".
num=2
if num > 3:
  print("A")
else:
  print("B")

In [ ]:
#53. Given a number 5, use if-elif-else to print "A" if >10, "B" if >3, otherwise "C".
num =5
if num > 10:
  print("A")
elif num > 3:
  print("B")
else:
  print("C")

In [ ]:
#54. Check whether a non-zero number is treated as True in a condition.
num = 7
if num:
    print("True")

In [ ]:
#55. Check whether 0 is treated as False in a condition.
num = 0
if num:
    print("True")
else:
    print("False")

In [ ]:
#56. Check if a list [1, 2] is non-empty and print "Non-empty".
x=[1,2]
if x:
  print("Non-empty")

In [ ]:
#57. Check if an empty list is empty and print "Empty".
x=[]
if not x:
  print("Empty")

In [ ]:
#58. Check whether element 2 exists in a set and print "Yes" if true.
x={1,2}
if 2 in x:
  print("Yes")

In [ ]:
#59. Check whether key "a" exists in a dictionary and print its value.
x={"a":1}
if "a" in x:
  print(x["a"])

In [ ]:
#60. Check if the length of a tuple (1,2) is equal to 2 and print "OK".
x = (1, 2)
if len(x) == 2:
    print("OK")

In [ ]:
#61. Print "Even" or "Odd" for a number using a conditional expression.
x= int(input("Enter a number: "))
print("Even" if x % 2 == 0 else "Odd")

In [ ]:
#62. Iterate through a list [1,2,3] and print each element.
x=[1,2,3]
for i in x:
  print(i)

In [ ]:
#63. Iterate through dictionary keys and print each key.
x={"a":1, "b":2}
for i in x:
  print(i)

In [ ]:
#64. Iterate through dictionary values and print each value.
x={"a":1, "b":2}
for i in x.values():
  print(i)

In [ ]:
#65. Iterate through a list and stop printing when a specific element is encountered.
lst = [1, 2, 3, 4, 5]
for x in lst:
    if x == 3:
        break
    print(x)

# March 24, 2026, Live session

In [ ]:
"""
Given a dictionary of students and their marks.
Add a new student
Update marks
Find the topper"""

students = {
    "Amit":56,
    "Aashish":70,
    "John":85
}

students["Priya"] = 95
students["Amit"] = 98

topper = max(students, key=students.get)
topper_marks = students[topper]

print("Students:", students)
print("Topper:", topper, "with", topper_marks, "marks")

In [ ]:
#Merge two dictionaries into one
x = {"a":1, "b":2}
y = {"c":3, "d":4}
x.update(y)
print (x)

In [ ]:
#Count how many times each word appears in a sentence.sentence = "apple banana apple orange banana apple"
sentance = "apple banana apple orange banana apple"
words = sentance.split()
print (words.count)                                  #this returns count in form of data id which only comuter can understand

for word in words:
  print(word, words.count(word))


from collections import Counter

sentence = "apple banana apple orange banana apple"
word_count = Counter(sentence.split())

print(word_count)

In [ ]:
l1=[1,2,3]
reversed(l1)
print (reversed(list(l1)))

for x in l1:
  print(x)

print(l1[::-1])

In [ ]:
from collections import OrderedDict
od = OrderedDict([('a',1),('b',2),('c',3)])

# March 25, 2026, OrderedDict

It will never loose the order.

It remebers the order in which keys are inserted

In [ ]:
from collections import OrderedDict

od = OrderedDict()
od['A']=1
od['B']=2
print (od)
print (list(od))                        #list(od) and list(od.keys()) shows same here.
print (list(od.keys()))
print(list(od.keys()),list(od.values()))
print(list(od.items()))

In [ ]:
od = OrderedDict([('apple',1),('Mango',2),('Banana',3)])
print (list(od.items()))

In [ ]:
# comparing dict and Ordered dict
from collections import OrderedDict

print("dict")
dict= {}
dict['a']=1
dict['b']=2
dict['c']=3
dict['d']=4

print(list(dict.items()))                 #to print in one line

for x,y in dict.items():                  # to print keys,values in different rows
  print(x,y)

print("\nOrdered Dict\n")
od= OrderedDict()
od['a']= 1
od['b']= 2
od['c']=3
od['d']=4

for key,value in od.items():
  print(key,value)

In [ ]:
from collections import OrderedDict

od1 = OrderedDict([('a', 1), ('b', 2), ('c', 3)])
od2 = OrderedDict([('c', 3), ('b', 2), ('a', 1)])  #checking hypothesis that does changing order would be same or different
print(od1 == od2)

In [ ]:
# Reversing Ordered Dictionary
mydict = OrderedDict([('Name','Marks'),('Amit',80),('John',88),('Rick',76)])
for name,mark in mydict.items():
  print(name,mark)
  print("\n")           #adding space after each item as I used it inside loop

#reversed function

mydict2 = OrderedDict(reversed(mydict.items()))
for name,mark in mydict2.items():
  print(name,mark)

#applying move to end function because I don't want Name and Marks in the bottom.
print("\n")                 # \n outside of loop
mydict2.move_to_end('Name',last = False)

for rename,remark in mydict2.items():
  print(rename,remark)

In [ ]:
# pop the first name and last name.

alpha = OrderedDict([('Amit',1),('Vega',2),('Cyber',3),('Jane Doe',4),('Mary Jane',5)])
alpha.popitem()
for x,y in alpha.items(): #removes last name
  print(x,y)
print("\n")
alpha.popitem('Amit')
for x,y in alpha.items():
  print(x,y)

print('\nInstead of removing Amit,Jane Doe got removed cause I used popitems not just pop')

print('\n\nlets try again and remove Amit from the list\n')

alpha.pop('Amit')
for x,y in alpha.items():
  print(x,y)

print('Amit got Kicked Out')

In [ ]:
# Move keys to front or end


alpha = OrderedDict([('Amit',1),('Vega',2),('Cyber',3),('Jane Doe',4),('Mary Jane',5)])
print('This is my original list')
for x,y in alpha.items():
  print (x,y)
print('\nMoving Amit to Last')

alpha.move_to_end('Amit')
for x,y in alpha.items():
  print(x,y)

print('\nmoving Jane Doe to last')

alpha.move_to_end('Jane Doe')
for x,y in alpha.items():
  print(x,y)

In [ ]:
#Deleting and re-inserting keys

alpha = OrderedDict([('Amit',1),('Vega',2),('Cyber',3),('Jane Doe',4),('Mary Jane',5)])
alpha.pop('Vega')           # removing vega from the list
for x,y in alpha.items():
  print(x,y)
print('\n')
alpha['Vega']= 2
for x,y in alpha.items():
  print(x,y)

In [ ]:
#trying something new                      I show a table on a Geeksfor Geeks Topic and want to create table like that

from collections import OrderedDict
table = OrderedDict()
table['Maintains insertion order']= OrderedDict()
table['Maintains insertion order']['Dict']='Yes'
table['Maintains insertion order']['OrderedDict']='Yes'

table['Allows key reordering']= OrderedDict()
table['Allows key reordering']['Dict']='No'
table['Allows key reordering']['OrderedDict']='Yes (move_to_end(key, last=True))'

table['Pop items from ends']=OrderedDict()
table['Pop items from ends']['Dict']='No (only popitem() removes last item)'
table['Pop items from ends']['OrderedDict']='Yes (popitem(last=True/False)supports both ends)'

table['Equality check consider orders']= OrderedDict()
table['Equality check consider orders']['Dict']='No (order ignored)'
table['Equality check consider orders']['OrderedDict']='Yes (order matters)'

table['Performance']= OrderedDict()
table['Performance']['Dict']='Faster'
table['Performance']['OrderedDict']='Slighly Slower'

print('Features                            | Dict                                  |OrderedDict')
print(('-'*35),'|',('-'*37),'|',('-')*50)
for keys,values in table.items():
  print(f"{keys:35} | {values['Dict']:37} | {values['OrderedDict']}")

In [ ]:
print('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')

# March 26, 2026, Live Session

In [ ]:
#Create an OrderedDict with keys 'a', 'b', 'c' and values 1, 2, 3. Print it.
from collections import OrderedDict
od= OrderedDict([('a',1),('b',2),('c',3)])
for x,y in od.items():
  print(x,y)

In [ ]:
#Insert elements into an OrderedDict and verify that order is preserved.
od= OrderedDict([('a',1),('b',2),('d',4)])
for x,y in od.items():
  print(x,y)

print('\n I am adding new element\n')
od['c']=3
for x,y in od.items():
  print(x,y)

In [ ]:
#Check whether two OrderedDicts with same elements but different order are equal.

alpha= OrderedDict([('a',1),('b',2),('c',3)])
beta= OrderedDict([('c',3),('b',2),('a',1)])

alpha == beta

In [ ]:
#Move key 'a' to the end of the dictionary.
alpha= OrderedDict([('a',1),('b',2),('c',3)])
alpha.move_to_end('a')
for x,y in alpha.items():
  print(x,y)

In [ ]:
dict= {}
dict['a']=1
dict['b']=2
dict['c']=3

print(type(dict))
print(list(dict.items()))
print(list(dict.items())[1])            #1 is a index number.Make sure to write index value outside of perenthesis brackets.
#print(dict.pop('b'))

print(list(dict.items())[0:2])

In [ ]:
#create a dictionary and return the key with maximum value

dict= {}
dict['a']=10
dict['b']=20
dict['c']=40

print(max,list(dict.items()))


d = {'a': 10, 'b': 20, 'c': 40}

max_key = max(dict, key=dict.get)
print (max_key,dict[max_key])

In [ ]:
# create a dictionary and return the key with 2nd maximum value

alpha = {'a':10,'b':35,'c':45,'d':37}
alphagen= sorted(alpha, key=alpha.get)[1]
print(alphagen,alpha[alphagen])

In [ ]:
# create a dictionary and return the key with 2nd maximum value
print('try with pop\n')
                                          #not recommended as intention is to find the value not to remove
alpha = {'a':10,'b':35,'c':45,'d':37}     #any existing item
max_alpha= max(alpha,key=alpha.get)
print(max_alpha,alpha[max_alpha])

# now use pop to remove max
max_alpha= alpha.pop(max_alpha)
print(alpha)

#print 2nd max value as a max value now
max_alpha= max(alpha,key=alpha.get)
print(max_alpha,alpha[max_alpha])

In [ ]:
#GCD of 2 numbers
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
while num1 != num2:
  if num1 > num2:
    num1 -= num2
  else:
    num2 -= num1
print(f"GCD: {num1}")

In [ ]:
##find second highest element in [13, 67, 43, 23, 12]

A = [13, 67, 43, 23, 12]

# March 31,2026, Numpy

NumPy is used because it gives Python fast, efficient, and powerful numerical
 computing capabilities that plain Python lists simply can’t match

- Doing math, statistics, ML, or data science
- Working with large datasets
- Needing fast operations
- Using matrices or multidimensional data

In [ ]:
#1D Arrays
import numpy as np
a = np.array([1,2,3])
print(a)

In [ ]:
#2D Arrays
b = np.array([[1,2,3],[4,5,6]])
print(b)

for x in b:
  for y in x:
    print(y)

In [ ]:
#3D Arrays     example-1
a= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)

In [ ]:
#3D Arrays    example-2
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

the difference  between both examples are not dimensionality — it’s the structure and size of each dimension

In [ ]:
#arrays filled with zeros
a = np.zeros(3)
print(a)

In [ ]:
a = np.zeros((2,3))          #option 1
print(a)

print('\n')               #first value present row, 2nd value present column

a= np.zeros([2,3])           #option 2
print(a)

In [ ]:
a= np.zeros([2,3,4])           #2 block, 3 rows each block, 4 columns each block
print(a)

In [ ]:
#arrays filled with ones

b=np.ones((3,3))
print (b)

In [ ]:
a = np.arange(10)
print(a)

In [ ]:
a = np.arange(-2,10)                                  #arange = array + range ?
print(a)                                              # answer- NO.
                                                      # their relation is like a==b but a is not b
b= np.array(range(-2,10))                             # np.arange() is faster than np.array(range())
print(b)

In [ ]:
a= np.array([1,2,3,4,5,6])
b= np.array([10,20,30,40,50,60])
c = np.add(a,b)
print(c)

d = np.subtract(a,b)
print(d)

e = np.multiply(a,b)
print(e)

In [ ]:
#linespace
a= np.linspace(1,10,4)
print(a)

In [ ]:
a= np.linspace([1,1,1],[2,2,2])
print(a)

In [ ]:
#using arange and reshape in numpy
a= np.arange(9).reshape(3,3)
print(a)

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)

In [ ]:
a= np.arange(1,28).reshape(3,3,3)
print(a)

In [ ]:
a = np.arange(-4,5).reshape(3,3)
print(a)

a= np.abs(a)
print(a)

# April 01,2026, slicing

In [ ]:
import numpy as np

a = np.array([12, 15, 10, 1])
print("Array before sorting",a)
a.sort()
print("Array after sorting",a)

In [ ]:
#show only 6,7,8
x = np.array([[1,2,3,4],[5,6,7,8]])

for a in x:
  for b in a:
    if b>5:
      print(b)

print(x[1][1::])                #correct way
print(x[1,1:4])                #also correct way

In [ ]:
#show 1,2,5

x = np.array([[1,2,3,4],[5,6,7,8]])

print(x[0:1,0:1])
print(x[0,0:2],[5])
print(x[[0,0,1],[0,1,0]])

In [ ]:
print(x[0,0:2],[1,::1])

Question 3

In [ ]:
x = np.array([[1,2,3,4],[5,6,7,8]])
b = [x[0][1]],[x[1][0]]
a = [x[0][0]]

In [ ]:
x = np.array([[1,2,3,4],[5,6,7,8]])                     #tried np.int64,np.concate,for loop,tolist()
                                                        #but mostly getting error or wrong answer or null
b = [x[0][1]],[x[1][0]]
a = [x[0][0]]

print(a,b)

In [ ]:
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8]])

a = [[int(x[0][0])]]
b = [int(x[0][1]), int(x[1][0])]

print(a, b)

In [ ]:
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8]])

one = int(x[0][0])
two = int(x[0][1])
five = int(x[1][0])

#answer 1: [[1,2],[5]]
print('answer 1')
a= [[one,two],[five]]
print(a,'\n')

#answer 2: [[[1,2,5]]]
print('answer2')
a = [[[one,two,five]]]
print(a,'\n')

#answer 3: [[1],[2],[5]]
print('answer3')
a = [[one],[two],[five]]
print(a,'\n')

#answer 4: [[1],[2,5]]
print('answer4')
a = [[one],[two,five]]
print(a,'\n')

#answer 5: [[[1],[2],[5]]]
print('answer5')
a = [[[one,two],[five]]]
print(a,'\n')

#Assignment 100 Ques.

In [ ]:
#1.Write a program to reverse a string without using slicing.

#option1
str1= input("enter something: ")
rev = " "
for i in str1:
  rev = i + rev
print(rev)

#option 2
x= " ".join(reversed(str1))                                                  #x=str(rev.reverse())>>>output: None
print(x)

#option 3   #using slicing
print(str1[::-1])

enter something: hello world
dlrow olleh
d l r o w   o l l e h
dlrow olleh

In [ ]:
#2. Write a function to check if a number is prime.

x = int(input("enter a number: "))
if x >1:
  for i in range(2,x):
    if (x % i) == 0:
      print(x, "is not a prime number")
      break
  else:
    print(x, "is a prime number")
else:
  print(x, "is not a prime number")

enter a number: 54
54 is not a prime number

In [ ]:
 #3. Find factorial of a number using recursion.
 # Recursion- A function calls itself again and again until it reaches a stopping point.

n = int(input("enter a number: "))
def fact(n):
  if n == 0:
    return 1
  else:
    return n * fact(n-1)
print (fact(n))

enter a number: 5
120

In [ ]:
#4. Find factorial using iteration.
#Iteration - Uses a loop (for or while) to repeat steps until the job is done.

n = int(input("enter a number "))
factorial =1
for i in range(1,n+1):
  factorial *= i
  print(factorial)

enter a number 4
1
2
6
24

In [ ]:
#5. Check if a string is a palindrome.
'''Palindrome: A string that reads the same forward and backward.
Examples:
- "madam"
- "racecar"
- "121"
- "noon"
'''
a = input("enter word, I will check palindrome: ")
rev = ""
for i in a:
  rev = i + rev
print(rev)

if a == rev:
  print(f'{a} is palindrome')
else:
  print(f'{a} is not palindrome')

enter word, I will check palindrome: naman
naman
naman is palindrome

In [ ]:
#6. Count vowels and consonants in a string.
word = input('enter word or sentence ').lower()
vowel = "aeiou"
v_counts =0
c_counts=0
for x in word:
  if x in vowel:
    v_counts +=1
  else:
    c_counts +=1
print("vowels: ",v_counts)
print("consonants: ",c_counts)

enter word or sentence hello world how are you
vowels:  8
consonants:  15

In [ ]:
#7. Find the largest element in a list.
lst = [10,20,15,2,25,19]
largest = lst[0]

for x in lst:
 if x > largest:
  largest = x
print(largest)

#option 2

lst.sort()
print(lst[-1])

25
25

In [ ]:
#8. Find the second largest element in a list.
lst = [10,20,15,2,25,19]
lst.sort()
print(lst[-2])

20

In [ ]:
#9. Remove duplicates from a list.
lst = [10,12,14,16,14,12,18,20]
for x in lst:
  if lst.count(x) > 1:
    lst.remove(x)
    lst.sort()
print(lst)

#option 2  #generated by Agent
lst = [10,12,14,16,14,12,18,20]
lst = list(dict.fromkeys(lst))
print(lst)

#option 3
lst= [10,12,14,16,14,12,18,20]
new_lst=[]

for i in lst:
  if i  not in new_lst:
    new_lst.append(i)
print(new_lst)

[10, 12, 14, 16, 18, 20]
[10, 12, 14, 16, 18, 20]
[10, 12, 14, 16, 18, 20]

In [ ]:
#10. Find common elements between two lists.

lst1= [10,2,12,13,15,18,19,20]
lst2= [5,10,15,20,25]

for i in lst1:
  for j in lst2:
    if i == j:
      print(i)

10
15
20

In [ ]:
#11. Swap two numbers without using a third variable.
a= 5
b= 4
print('Original numbers are ',a,'',b)
a,b=b,a
print('Interchanged numbers are ',a,b)

Original numbers are  5  4
Interchanged numbers are  4 5

In [ ]:
#12. Count frequency of each character in a string.
str_1= input('enter your word: ')
n_str=""

for x in str_1:
  if x not in n_str:             #to ensure no duplicates would be there
    print(x,str_1.count(x))
    n_str += x

enter your word: i dont want to write
i 2
  4
d 1
o 2
n 2
t 4
w 2
a 1
r 1
e 1

In [ ]:
#13. Find sum of digits of a number.

a= (input('enter number: '))
sum=0
for i in a:
    sum = sum + int(i)            #sum= sum + int(a) make the value double
print(sum)

enter number: 54
9

In [ ]:
#14. Reverse digits of a number.
a= (input('enter a number: '))
print(a[::-1])

enter a number: 45
54

In [ ]:
#15. Check if a number is Armstrong. #somewhere in this assignment I used same keyword so its giving error code is working
a = int(input("Enter a number: "))

n = len(str(a))

total = sum(int(x)**n for x in str(a))

if total == a:
    print(a, "is an Armstrong number")
else:
    print(a, "is not an Armstrong number")

Enter a number: 4

TypeError: 'int' object is not callable

In [ ]:
#15. Check if a number is Armstrong.
a = int(input("Enter a number: "))

digits = str(a)
n = len(digits)

total = sum(int(x)**n for x in digits)

if total == a:
    print(a, "is an Armstrong number")
else:
    print(a, "is not an Armstrong number")

In [ ]:
#16. Generate Fibonacci series up to N.
#The Fibonacci series is a sequence of numbers where each number is the sum of the previous two numbers.

n = int(input("Enter N: "))

a, b = 0, 1

print("Fibonacci series:")

while a <= n:
    print(a, end=" ")
    a, b = b, a + b

Enter N: 45
Fibonacci series:
0 1 1 2 3 5 8 13 21 34

In [ ]:
#17. Find GCD of two numbers.
#GCD (Greatest Common Divisor) of two numbers is the largest number that divides
#both numbers exactly (without leaving a remainder).

import math

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("GCD =", math.gcd(a, b))

Enter first number: 45
Enter second number: 54
GCD = 9

In [ ]:
#18. Find LCM of two numbers.
#LCM (Least Common Multiple) of two numbers is the smallest number that both numbers divide into exactly.

import math

a= int(input("Enter first number: "))
b= int(input("Enter second number: "))

print("LCM =", math.lcm(a,b))

Enter first number: 45
Enter second number: 95
LCM = 855

In [ ]:
#19. Count words in a sentence.
a= input('write a sentance: ')
print(len(a))

write a sentance: helooooo worrrooolllddd
23

In [ ]:
#20. Find maximum occurring character in string.
a = input("Enter a sentance: ")
max_a= ""
max_char= ""
max_count=0
for x in a:
  if x not in max_a:
    print(x,a.count(x))
    max_a += x

    if a.count(x) > max_count:
      max_count = a.count(x)
      max_char = x
print('max ocuuring character is ',max_char)
      #spacebar is also a character

Enter a sentance: mswkdjaqd
m 1
s 1
w 1
k 1
d 2
j 1
a 1
q 1
max ocuuring character is  d

In [ ]:
#21. Sort a list without using sort().
lst=[15,22,13,84,50]
for i in range(len(lst)):
  for j in range(i+1,len(lst)):
    if lst[i] > lst[j]:
      lst[i],lst[j]=lst[j],lst[i]
print(lst)

[13, 15, 22, 50, 84]

In [ ]:
#22. Find missing number in list (1 to N).
lst=[1,2,3,4,5,7,8,9,10,13,14,15,16,17,18,19,20]
misslist=[]
'''for i in lst:
  if i not in lst:                        #unable to decide when to use for loop and when to use if statement when questions like this occurs.
    misslist.append(i)                    #using for loop was giving syntax error here need to understand why
    i +=1
print(misslist)             #not working
'''
for i in range(lst[0],lst[-1]+1):                 #i can also use min and max logic...will try
  if i not in lst:
    misslist.append(i)
print(misslist)


#option-2                #only using (min(lst)) gives me [6,11,12,0]
for i in range(min(lst),max(lst)+1):
  if i not in lst:
    misslist.append(i)
print(misslist)             #6,11,12,6,11,12 is showing because I tried both way. If I put option 1 in comment then
                            # option 2 is showing me only 6,11,12 which is desired output.

[6, 11, 12]
[6, 11, 12, 6, 11, 12]

In [ ]:
#23. Find all even numbers from a list.
lst= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

print('Option 1')
for i in lst:
 if i%2==0:
  print(i)
print('\n')

print('option2')
for i in range(len(lst)):
  if lst[i]%2==0:
    print(lst[i])
print('\n')

print('option3')
for i in range(min(lst),max(lst)+1):
  if i%2==0:
    print(i)
print('\n')

print('option4')     #by using 2 I was able to skip 1 number and print another but showing me odd numbers so i used slicing to start showing me numbers from 2
for i in range(min(lst[1::]),max(lst)+1,2):
  print(i)
print('\n')

print('option5')
for i in range(lst[0],lst[-1]+1):
    if i%2==0:
      print(i)

Option 1
2
4
6
8
10
12
14
16
18
20


option2
2
4
6
8
10
12
14
16
18
20


option3
2
4
6
8
10
12
14
16
18
20


option4
2
4
6
8
10
12
14
16
18
20


option5
2
4
6
8
10
12
14
16
18
20

In [ ]:
#25. Check if two strings are anagrams.

str1 = input("Enter first string: ").lower()
str2 = input("Enter second string: ").lower()
for i in str1:
    if sorted(str1) == sorted(str2):
      print("Anagrams")
    else:
      print("Not Anagrams")

Enter first string: anagarm here
Enter second string: not here
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams
Not Anagrams

In [ ]:
#26. Remove all spaces from a string.
l1= input("enter a string: ")
print(l1.replace(" ",""))

enter a string: dwdf edfef h   rge   eg
dwdfedfefhrgeeg

In [ ]:
#27. Find longest word in a sentence.
l1= input("enter a sentence: ").split()
print(max(l1,key=len))

enter a sentence: qwerty uiop asdfghjkl
asdfghjkl

In [ ]:
#28. Replace all vowels with *.
word = input('enter word or sentence ').lower()
vowel = "aeiou"

for x in word:
  if x in vowel:
    word = word.replace(x,"*")
print(word)

enter word or sentence hello mars
h*ll* m*rs

In [ ]:
#29. Count number of uppercase and lowercase letters.
word = input('enter word or sentence ')

upper=" "
lower=" "
for x in word:
  if x.isupper():
    upper += x
  else:
    lower += x
print("upper case letters: ",len(upper)-1)
print("lower case letters: ",len(lower)-1)      #spacebar counting as lowercase  will try to remove later

enter word or sentence HomE CominG
upper case letters:  4
lower case letters:  7

In [ ]:
#31. Flatten a nested list. Flattening means turning this multi‑level structure into a single list with no inner lists.
lst= [[1,2,[3,4,5]],[2,4,6,8,10]]
print(lst,'\n')
flat_lst=[]
"""for i in lst:
  if i not in flat_lst:
    flat_lst.append(i)         #this logic is not working here
print(flat_lst)"""

for i in lst:
  if isinstance(i,list):
    for j in i:
      flat_lst.append(j)
  else:
    flat_lst.append(i)
print(flat_lst)                #not working for deep nesting

[[1, 2, [3, 4, 5]], [2, 4, 6, 8, 10]]

[1, 2, [3, 4, 5], 2, 4, 6, 8, 10]

In [ ]:
#31. Flatten a nested list. Flattening means turning this multi‑level structure into a single list with no inner lists.
#option2
lst= [[1,2,[3,4,5]],[2,4,6,8,10]]
flat_lst=[]
for i in lst:
  if isinstance(i,list):
    for j in i:
      if isinstance(j,list):
        for k in j:
          flat_lst.append(k)
      else:
        flat_lst.append(j)
  else:
    flat_lst.append(i)
print(flat_lst)

[1, 2, 3, 4, 5, 2, 4, 6, 8, 10]

In [ ]:
#32. Rotate a list by k elements.
lst= [1,2,3,4,5,6,7,8,9,10]
k= int(input("enter a number: "))
print(lst[k:]+lst[:k])
print(lst[-k:]+lst[:-k])

enter a number: 5
[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]
[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]

In [ ]:
#33. Find all pairs with given sum.
lst= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,24,25,30,33,36,39]
target= int(input("enter a number: "))
for i in range(len(lst)):
  for j in range(i+1,len(lst)):
    if lst[i] + lst[j] == target:
      print(lst[i],lst[j])

enter a number: 54
15 39
18 36
24 30

In [ ]:
#34. Remove all occurrences of an element from list.
lst= [1,2,3,4,5,6,2,3,4,6]
target= int(input("which number you don't want in the list? : "))
for i in lst:
  if i == target:
    lst.remove(i)
print(lst)

which number you don't want in the list? : 3
[1, 2, 4, 5, 6, 2, 4, 6]

In [ ]:
#35. Find intersection of two lists without using set.   #common element
lst1= [1,2,3,4,5,6,7,8,9,10]
lst2= [2,4,5,6,7,8,9]

for i in lst1:
  for j in lst2:
    if i == j:
      print(i)

2
4
5
6
7
8
9

In [ ]:
#36. Convert list of strings to integers.
lst= ['1','2','3','4','5']
for i in range(len(lst)):
  lst[i]= int(lst[i])
print(lst)

[1, 2, 3, 4, 5]

In [ ]:
#37. Find all substrings of a string.
str1= input("enter a string: ")
substr1=" "
for i in range(len(str1)):
  for j in range(i+1,len(str1)+1):
    substr1 = str1[i:j]
    print(substr1)

enter a string: hello
h
he
hel
hell
hello
e
el
ell
ello
l
ll
llo
l
lo
o

In [ ]:
#38. Check if string contains only digits.
str1 = input("enter a string: ")

if str1.isdigit():
    print("contains only digits")
else:
    print("does not contain only digits")        #54 contains digit but 54.0 does not contains only digits

enter a string: 54
contains only digits

In [ ]:
#39. Remove punctuation from string.
import string
a= input("enter a string: ")
new_a= " "
for i in a:
  if i not in string.punctuation:
    new_a += i
print(new_a)

enter a string: canada eh!!!!
 canada eh

In [ ]:
#40. Find first non-repeating character.
str1 = input("enter a string: ")
str2 = ""

for ch in str1:
    if str1.count(ch) == 1:
        str2 += ch

if str2:
    print("first non-repeating character:", str2[0])
else:
    print("no non-repeating character found")

enter a string: first non repeat
first non-repeating character: f

In [ ]:
#41. Find longest substring without repeating characters.
alpha= input("enter a string: ")
longest_substring = ""
current_substring = ""
for i in alpha:
  if i not in current_substring:
    current_substring += i

    if len(current_substring) > len(longest_substring):
      longest_substring = current_substring

  else:
    current_substring = ""
print(longest_substring)

enter a string: first non repeat
first no

In [ ]:
#42. Count occurrences of substring.
str1 = input("enter a string: ")
substr1 = input("enter a substring: ")
print(str1.count(substr1))

enter a string: heli
enter a substring: he
1

In [ ]:
#43. Reverse words in a sentence.
str1 = input("enter a string: ")
print(str1[::-1])

enter a string: hello
olleh

In [ ]:
#44. Check if two lists are identical.
lst1= [1,2,3,4,5,6]
lst2= [1,2,3,4,5,6]
if lst1 == lst2:
  print("identical")
else:
  print("not identical")

identical

In [ ]:
#45. Group anagrams from list of strings.             #need help
lst1= ["eat","tea","tan","ate","nat","bat","cat","tab","pet"]
lst2=[]

In [ ]:
#46. Find all permutations of a string.
from itertools import permutations

s = input("enter a string: ")

for p in permutations(s):
    print("".join(p))

enter a string: polo
polo
pool
ploo
ploo
pool
polo
oplo
opol
olpo
olop
oopl
oolp
lpoo
lpoo
lopo
loop
lopo
loop
opol
oplo
oopl
oolp
olpo
olop

In [ ]:
#47. Find duplicate elements in list.
lst=[1,2,3,4,5,6,6,7,8,9,2,3]
lst2=[]
for i in lst:
  if i not in lst2:
    lst2.append(i)
  else:
    print(i)

6
2
3

In [ ]:
#48. Split list into chunks of size N.
lst=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

In [ ]:
#49. Find median of a list.
import numpy as np

lst=[1,2,3,4,5,6,7,8,9]
def med(lst):
    return np.median(lst)
print(med(lst))

5.0

In [ ]:
#50. Find mode of a list.
lst=[1,2,3,4,5,6,7,8,9,2,2,3]

def mode(lst):
    return max(set(lst), key=lst.count)
print(mode(lst))

2

In [ ]:
#51. Create a dictionary from two lists (keys & values).
x = ['a','b','c','d']
y= [1,2,3,4]

print(dict(zip(x,y)))

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [ ]:
#52. Find key with maximum value in dictionary.
x= {'a':1,'b':2,'c':3,'d':4}
print(max(x, key=x.get))

d

In [ ]:
#53. Sort dictionary by values.

In [ ]:
#54. Merge two dictionaries.
a= {'a':1,'b':2,'c':3,'d':4}
b={'aa':10,'bb':20,'cc':30,'dd':40}
print(a|b)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'aa': 10, 'bb': 20, 'cc': 30, 'dd': 40}

In [ ]:
#55. Count frequency of elements using dictionary.
lst=[1,2,3,4,5,6,6,7,8,9,2,3]
lst2=[]
for i in lst:
  if i not in lst2:
    lst2.append(i)
    print(i,lst.count(i))

1 1
2 2
3 2
4 1
5 1
6 2
7 1
8 1
9 1

In [ ]:
#56. Invert a dictionary (swap keys and values).
dictionary={'a':1,'b':2,'c':3}
print(dict((v,k) for k,v in dictionary.items()))

{1: 'a', 2: 'b', 3: 'c'}

In [ ]:
#57. Find common keys in two dictionaries.
x = {'a': 1, 'b': 2, 'c': 3}
y = {'b': 2, 'c': 4, 'd': 5}

common_keys = set(x).intersection(y)
print(common_keys)

{'b', 'c'}

In [ ]:
#58. Remove a key from dictionary safely.
x = {'a': 1, 'b': 2, 'c': 3}
x.pop('a')
print(x)

{'b': 2, 'c': 3}

In [ ]:
#59. Find sum of all values in dictionary.
x = {'a': 1, 'b': 2, 'c': 3,'d':10}
print(sum(x.values()))

TypeError: 'int' object is not callable

In [ ]:
#60. Convert dictionary to list of tuples.
x = {'a': 1, 'b': 2, 'c': 3}
print(list(x.items()))

[('a', 1), ('b', 2), ('c', 3)]

In [ ]:
#61. Group list elements by frequency.

from collections import Counter

lst = [1,2,3,4,5,6,6,7,8,9,2,2,3]

freq = Counter(lst)
print(freq)

Counter({2: 3, 3: 2, 6: 2, 1: 1, 4: 1, 5: 1, 7: 1, 8: 1, 9: 1})

In [ ]:
#62. Find elements appearing more than once.
lst = [1,2,3,4,5,6,6,7,8,9,2,3]
lst2=[]
for i in lst:
  if i not in lst2:
    lst2.append(i)
  else:
    print(i)

6
2
3

In [ ]:
#63. Check if two dictionaries are equal.
a= {'a':1,'b':2,'c':3,'d':4}
b={'aa':10,'bb':20,'cc':30,'dd':40}
print(a==b)

False

In [ ]:
#64. Find union of two sets.
a= {1,2,3,4,5,6}
b={7,8,9,10,11,12}

print(a|b)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

In [ ]:
#65. Find difference of two sets.
b= {1,2,3,4,5,6}
a={7,8,9,10,11,12}
print(b-a)

{1, 2, 3, 4, 5, 6}

In [ ]:
#66. Remove duplicates using set.
lst=[1,2,3,4,5,6,6,7,8,9,2,3]
print(set(lst))

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
#67. Check subset and superset.
a= {1,2,3,4,5,6}
b={7,8,9,10,11,12}
print(a.issubset(b))
print(a.issuperset(b))

False
False

In [ ]:
#68. Find symmetric difference of sets.
#The symmetric difference returns elements that are in either set, but not in both.
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

a= {1,2,3,4,5,6,7,8}      #     ^ is a known for symmetric diffenece.
b={7,8,9,10,11,12}        # 7,8 are common in both the list so its not gonna print in the output
print(a^b)

{1, 2, 3, 4, 5, 6, 9, 10, 11, 12}

In [ ]:
#69. Count unique elements in list.
lst=[1,2,3,4,5,6,6,7,8,9,2,3,4,5,6,7,8,9]
lst2= []
for i in lst:
  if i not in lst2:
    lst2.append(i)
print(len(lst2))

9

In [ ]:
#70. Find intersection of multiple lists.
lst1= [1,2,3,4,5,6]
lst2= [2,4,5,6,7,8]
lst3= [3,4,5,6,7,8]
x = (set(lst1).intersection(lst2,lst3))     # no need to use def function
print(list(x))

[4, 5, 6]

Recursion is elegant, but not always practical.
Recursion is a bad idea when:
- the depth becomes too large
- the problem has overlapping subproblems (like Fibonacci)
- an iterative solution is simpler and faster
- Python’s recursion limit (≈1000) will be exceeded
- memory usage becomes too high
Examples where recursion is not ideal:
- Fibonacci (naive)
- Factorial for huge numbers
- Deep tree traversal without tail recursion
- Large linked list processing
Examples where recursion is ideal:
- DFS on graphs
- Tree traversal
- Divide‑and‑conquer algorithms (merge sort, quicksort)
- Backtracking (Sudoku, permutations)

In [ ]:
#71. Write recursive function for Fibonacci.

n= int(input("enter a number: "))

def fib(n):                                          #if n<=1 return n is known as base case.
    if n <= 1:                                #base case is a condition to stops the recursion.
        return n
    return fib(n-1) + fib(n-2)          #In fib(n):- here 'n' is a known as a  recursion depth
                                        #if n= 6 then it has 6 recursion depth
'''bigger the number of n then:- it will be more slow down
                                                                       - Stack oveflow
                                                                       - exponential time complexity
                                                                       '''
print(fib(n))


'''Once you understand recursive Fibonacci, you can understand:
- Dynamic programming
- Memoization
- Divide‑and‑conquer algorithms
- Tree recursion
- Backtracking
- Graph traversal (DFS)
'''

enter a number: 6
8

'Once you understand recursive Fibonacci, you can understand:\n- Dynamic programming\n- Memoization\n- Divide‑and‑conquer algorithms\n- Tree recursion\n- Backtracking\n- Graph traversal (DFS)\n'

In [ ]:
#72. Write recursive binary search.

'''

Help

'''

'\n\nHelp\n\n'

In [ ]:
#73. Write function to check palindrome (recursion).               #A string of length 0 or 1 is always a palindrome.
s= input("enter a string: ")
def is_palindrome(s):

    if len(s) <= 1:
        return True
    if s[0] != s[-1]:
        return False
    return is_palindrome(s[1:-1])
print(is_palindrome(s))

enter a string:
True

In [ ]:
#74. Write function to flatten nested list (recursion).
lst= [[1,2,[3,4,5]],[2,4,6,8,10]]
def flatten(lst):
    flat = []
    for item in lst:
        if isinstance(item, list):
            flat.extend(flatten(item))   # recursive step
        else:
            flat.append(item)            # base case
    return flat
print(flatten(lst))

[1, 2, 3, 4, 5, 2, 4, 6, 8, 10]

In [ ]:
#75. Calculate power (x^n) using recursion.
x= int(input("enter a number: "))
n= int(input("enter a number: "))
def power(x, n):
    if n == 0:
        return 1
    return x * power(x, n - 1)
print(power(x, n))

enter a number: 4
enter a number: 8
65536

In [ ]:
#76. Write function to check if number is even using lambda.
x= int(input("enter a number: "))
even = lambda x: x % 2 == 0
print('Even :',even(x))

enter a number: 8
Even : True

In [ ]:
#77. Use map() to square list elements.
lst= [1,2,3,4,5,6,7,8,9]
print(list(map(lambda x: x**2, lst)))

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
#78. Use filter() to get odd numbers.
lst= [1,2,3,4,5,6,7,8,9]
print(list(filter(lambda x: x%2!=0, lst)))

[1, 3, 5, 7, 9]

In [ ]:
#79. Use reduce() to find product of list.
from functools import reduce

numbers = [2, 3, 4, 5]

product = reduce(lambda x, y: x * y, numbers)
print(product)

120

In [ ]:
#80. Write decorator to measure execution time.

In [ ]:
#81. Write closure example.

x = int(input("enter a number for outer function: "))
y= int(input("enter a number for inner function: "))
def outer_function(x):
    def inner_function(y):
        return x + y
    return inner_function
closure = outer_function(5)
result = closure(10)
print(result)

enter a number for outer function: 8
enter a number for inner function: 4
15

In [ ]:
#82. Write function with variable arguments (*args).
args = input("enter a number: ")
def show_args(*args):
    print(args)

                                              #not sure my answer is correct or not. need to discuss
show_args(*args)

enter a number: 45
('4', '5')

In [ ]:
#83. Write function with keyword arguments (**kwargs).
kwargs = input("enter a number: ")
def show_kwargs(**kwargs):
 print(kwargs)                 ##not sure my answer is correct or not. need to discuss
show_args(*args)

enter a number: 54568
('4', '5')

In [ ]:
#84. Write generator for even numbers.
x = int(input("enter a number: "))
def even_numbers(x):
    for i in range(x):
        if i % 2 == 0:
            yield i
            print(i)
even_numbers(x)

enter a number: 54

In [ ]:
#85. Write generator for Fibonacci sequence.

n= int(input("enter a number(depth): "))
def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b
        print(a)
fibonacci(n)

enter a number(depth): 6

In [ ]:
#86. Write program to detect duplicates in list efficiently.
lst = [1,2,3,4,5,6,6,7,8,9,2,3,4,5]
lst2=[]
for i in lst:
  if i not in lst2:
    lst2.append(i)
  else:
        print(i)

6
2
3
4
5

In [ ]:
#87. Find first repeating element in list.
lst = [1,2,3,4,5,6,6,7,8,9,2,3,4,5]
lst2=[]
duplicates=[]
for i in lst:
  if i not in lst2:
    lst2.append(i)
  else:
        duplicates.append(i)
print(lst3[0])

3

In [ ]:
#88. Find pair with maximum sum.
arr = [1,2,3,4,5,6,7,8,9]
def max_sum_pair(arr):
    if len(arr) < 2:
        raise ValueError("Array must contain at least two elements")

    max1 = max(arr[0], arr[1])
    max2 = min(arr[0], arr[1])

    for x in arr[2:]:
        if x > max1:
            max2 = max1
            max1 = x
        elif x > max2:
            max2 = x

    return (max1, max2), max1 + max2
print(max_sum_pair(arr))

((9, 8), 17)

In [ ]:
#89. Implement your own len() function.
lst= [1,2,3,4,5,6,7,8,9]
def my_len(lst):
    count = 0
    for x in lst:
        count += 1
    return count
    print(count)
my_len(lst)

9

In [ ]:
#90. Implement your own max() function.
lst= [1,22,3,48,5,61,70,8,9,16]
def my_max(lst):
    max_value = lst[0]
    for x in lst:
        if x > max_value:
            max_value = x
    return max_value
print(my_max(lst))

70

In [ ]:
#91. Implement stack using list.

"""
help
"""

'\nhelp\n'

In [ ]:
#92. Implement queue using list.
"""
help
"""

'\nhelp\n'

In [ ]:
#93. Reverse a stack using recursion.
"""
help
"""

'\nhelp\n'

In [ ]:
#94. Check balanced parentheses.
expr = input("Enter an expression: ")
def is_balanced(expr):
    stack = []
    pairs = {')': '(', '}': '{', ']': '['}

    for ch in expr:
        if ch in "({[":
            stack.append(ch)
        elif ch in ")}]":
            if not stack or stack.pop() != pairs[ch]:
                return False

    return len(stack) == 0

if is_balanced(expr):
    print("Balanced")
else:
    print("Not Balanced")

Enter an expression: (5 + 7 * {4 + 3 - 1]}
Not Balanced

In [ ]:
#95. Convert decimal to binary.
decimal = int(input("Enter a decimal number: "))

def decimal_to_binary(decimal):
    if decimal == 0:
        return "0"
    binary = ""
    while decimal > 0:
        binary = str(decimal % 2) + binary
        decimal //= 2
    return binary

print(decimal_to_binary(decimal))

Enter a decimal number: 10
1010

In [ ]:
#96. Convert binary to decimal.
binary = input("Enter a binary number: ")

def binary_to_decimal(binary):
    decimal = 0
    power = 0

    for digit in reversed(binary):
        decimal += int(digit) * (2 ** power)
        power += 1

    return decimal

print(binary_to_decimal(binary))

Enter a binary number: 1010
10

In [ ]:
#97. Find longest consecutive sequence in list.
lst = [100, 4, 200, 1, 5, 2,4,5,6]
def longest_consecutive(nums):
    if not nums:
        return 0

    num_set = set(nums)
    longest = 0

    for n in num_set:
        # Check if n is the start of a sequence
        if n - 1 not in num_set:
            length = 1
            current = n

            # Count forward
            while current + 1 in num_set:
                current += 1
                length += 1

            longest = max(longest, length)

    return longest


print("Longest consecutive sequence length:", longest_consecutive(lst))

Longest consecutive sequence length: 3

In [ ]:
#98. Move all zeros to end of list.
lst = [1,2,3,4,5,0,0,6,7,8]
for i in lst:
  if i==0:
    lst.remove(i)
    lst.append(i)
    print(lst)

[1, 2, 3, 4, 5, 0, 6, 7, 8, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 0, 0]

In [ ]:
#99. Find majority element in list.
lst = [1,2,3,4,5,6,6,7,8,9,2,3,7,2]
def majority_element(lst):
  if not lst:
    return None
  count = 1
  candidate = lst[0]
  for i in range(1, len(lst)):
    if lst[i] == candidate:
      count += 1
    else:
      count -= 1
      if count == 0:
        candidate = lst[i]
        count = 1
  return candidate
print(majority_element(lst))

2

In [ ]:
#100. Implement simple calculator (add, subtract, multiply, divide).
num1 = float(input("Enter first number: "))
op = input("Enter operator (+, -, *, /): ")
num2 = float(input("Enter second number: "))

def calculator(a, operator, b):
    if operator == "+":
        return a + b
    elif operator == "-":
        return a - b
    elif operator == "*":
        return a * b
    elif operator == "/":
        if b == 0:
            return "Error: Division by zero"
        return a / b
    else:
        return "Invalid operator"


result = calculator(num1, op, num2)
print("Result:", result)

Enter first number: 5
Enter operator (+, -, *, /): +
Enter second number: 15
Result: 20.0

# April 03 2026, Live Session

In [ ]:
import numpy as np                                #need to remind Ashish
lst=np.array([1,2,3,4,5],[2,3,4,5,6])
print(lst[0:2,1:4])

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
print(arr[-3:-1])
print(arr[1:5:2])

In [ ]:
#2-D Array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

print(arr[0:2, 2])

In [ ]:

print(arr[0:2, 1:3])

In [ ]:
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arr[0, 2:4], arr[1, 2:4])

# April 04,2026

In [ ]:
#Create a NumPy array from 1 to 10 and extract elements from index 2 to 6.
arr= np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2:7])

In [ ]:
#Extract every alternate element from the array.
arr= np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0:10:2])       #not ideal
print(arr[::2])           #for odd numbers
print(arr[1::2])        #for even numbers

In [ ]:
#Reverse a NumPy array using slicing.
arr= np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::-1])

In [ ]:
#Extract the 2nd row from a 2D array.
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr[1,::])

In [ ]:
#Change middle elements to 0 using slicing.
arr= np.array([1,2,3,4,5,6,7,8,9,10])
arr[4:6]=0
print(arr)

In [ ]:
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
arr[0,2],arr[1,2]=0,0
print(arr)

[[ 1  2  0  4  5]
 [ 6  7  0  9 10]]

# April 07,2026

In [ ]:
import numpy as np
a1= [[[1,2,3],[4,45,2]],[[3,4,5],[7,3,5]]]

for x in a1:
  print(x)

[[1, 2, 3], [4, 45, 2]]
[[3, 4, 5], [7, 3, 5]]

In [ ]:
a1= [[[1,2,3],[4,45,2]],[[3,4,5],[7,3,5]]]

for x in a1:
  for y in x:
    print(y)

[1, 2, 3]
[4, 45, 2]
[3, 4, 5]
[7, 3, 5]

In [ ]:

# Homework Question


import numpy as np
a1= np.array([1,2,3])
a2= np.array([4,5,6])
a1=a1.tolist()           #tolist only works with numpy array
a2=a2.tolist()     #to avoid complecation later I used tolist before iteration

a4=[]
for i in a1:
  if i not in a4:
    a4.append(i)
for j in a2:
  if j not in a4:
    a4.append(j)
print(a4)
'''
initially when Ashish asked us to print both arrays I want to try to solve using Iteration.
I tried various ways such as

trial-1

a1= np.array([1,2,3])
a2= np.array([4,5,6])
a4=[]

for i in a1:
  for j in a2:
    if i not in a4:
      a4.append(i)
    if j not in a4:
      a4.append(j)
print(a4)

output:-[np.int64(1), np.int64(4), np.int64(5), np.int64(6), np.int64(2), np.int64(3)]


trial-2
a1= np.array([1,2,3])
a2= np.array([4,5,6])
a4=[]

for i in a1:
  for i in a2:
    if i not in a4:
      a4.append(i)
print(a4)

output:- [np.int64(4), np.int64(5), np.int64(6)]

trial-3
a1= np.array([1,2,3])
a2= np.array([4,5,6])
a4=[]

for i in a1:
  for j in a2:
    if (i+j) not in a4:
      a4.append(i+j)
print(a4)
output:-[np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]'''

[np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]

Practice converting between:
•	String → Integer
•	Integer → Float
•	Float → Integer

In [ ]:
#Convert a NumPy Array to a String
a1= np.array([1, 2, 3])
print(a1,type(a1))
s = a1.astype(str)
print('\nString: ',s,type(s))     #astype(str) does not give you one big string.It gives you an array of strings.
print(s.dtype)
"""
Notes:
output:- U21   where U means Unicode String. 21 is max space for the character.
my character space is currently 1 so it should show me U1 but somewhere in the past I have
given 21 characters to the a1 so even after I overwrite the a1 character space can't be resize automatically.
but it can be resize manually by using tolist
"""
print('To reset the dtype to minimal size')
s = np.array(s.tolist(), dtype=str)
print(s.dtype)
#converting String to Integer
print('\nConvert string to int')
i= s.astype(int)
print('Integer: ',i)             #arrays of int.
print(i.dtype,':- This says we converted to integer')

print('\nlets convert this integer to float')
f=i.astype(float)
print('Float: ',f)
print(f.dtype,':- This says we converted to float')

print('\nlets convert this float to integer')
i=f.astype(int)
print('Integer: ',i)
print(i.dtype,':- This says we converted to integer')

[1 2 3] <class 'numpy.ndarray'>

String:  ['1' '2' '3'] <class 'numpy.ndarray'>
<U21
To reset the dtype to minimal size
<U1

Convert string to int
Integer:  [1 2 3]
int64 :- This says we converted to integer

lets convert this integer to float
Float:  [1. 2. 3.]
float64 :- This says we converted to float

lets convert this float to integer
Integer:  [1 2 3]
int64 :- This says we converted to integer

Stacking Arrays

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.stack([a, b])
print(c)

d= np.stack([a, b],axis=1)
print('\n',d)

e= np.vstack([a, b])
print('\nvstack',e)

f= np.hstack([a, b])
print('\nhstack',f)

g= np.dstack([a, b])
print('\ndstack',g)

h= np.concatenate([a, b])
print('\nconcatenate',h)

[[1 2 3]
 [4 5 6]]

 [[1 4]
 [2 5]
 [3 6]]

vstack [[1 2 3]
 [4 5 6]]

hstack [1 2 3 4 5 6]

dstack [[[1 4]
  [2 5]
  [3 6]]]

concatenate [1 2 3 4 5 6]

In [ ]:
print("shape:", c.shape)
# shape → tuple showing dimensions of the array (rows, cols, etc.)

print("ndim:", c.ndim)
# ndim → number of dimensions (axes)

print("size:", c.size)
# size → total number of elements in the array

print("dtype:", c.dtype)
# dtype → data type of each element (int32, float64, <U21, etc.)

print("itemsize:", c.itemsize)
# itemsize → bytes used by ONE element

print("nbytes:", c.nbytes)
# nbytes → total memory used by the array (size * itemsize)

print("strides:", c.strides)
# strides → how many bytes to move in each dimension to get to the next element

print("flags:", c.flags)
# flags → memory layout info (C‑contiguous, F‑contiguous, writeable, aligned, etc.)

print("base:", c.base)
# base → reference to original array if this is a view; None if it owns its data

print("data:", c.data)
# data → low‑level memory buffer address (pointer-like)

print("view():", c.view())
# view() → creates a new view of the same data (no copy)

print("copy():", c.copy())
# copy() → creates a full, independent copy of the array

print("tolist():", c.tolist())
# tolist() → converts NumPy array to a regular Python list

shape: (2, 3)
ndim: 2
size: 6
dtype: int64
itemsize: 8
nbytes: 48
strides: (24, 8)
flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

base: None
data: <memory at 0x7e0278527ed0>
view(): [[1 2 3]
 [4 5 6]]
copy(): [[1 2 3]
 [4 5 6]]
tolist(): [[1, 2, 3], [4, 5, 6]]

Splitting Methods

In [ ]:
import numpy as np
arr = np.arange(6)
arr2 = np.split(arr, 2)
print(arr2)

[array([0, 1, 2]), array([3, 4, 5])]

In [ ]:

arr = np.arange(13)
arr2 = np.array_split(arr, 1)
arr3= np.array_split(arr, 2)
arr4= np.array_split(arr, 3)
print(arr2)
print(arr3)
print(arr4)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])]
[array([0, 1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr2 = np.vsplit(arr, 1)
arr3= np.vsplit(arr, 2)
arr4= np.vsplit(arr, 4)
print(arr2,'\n')
print(arr3,'\n')
print(arr4,'\n')

[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]

In [ ]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a2 = np.hsplit(arr, 2)
a3= np.hsplit(arr,1)
print(a2,'\n')
print(a3,'\n')

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])]

# April 08,2026

In [ ]:
#Create a 2D NumPy array and print its shape.

import numpy as np

a1= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a1.shape)

(2, 5)

In [ ]:
#Create a 1D and a 2D array using np.array().

a1= np.array([1,2,3,4,5,6])
a2= np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(a1)
print('\n',a2)

[1 2 3 4 5 6]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

In [ ]:
#Reshape an array of 10 elements into shape (5,2).
a1= np.array([1,2,3,4,5,6,7,8,9,10])
a2= a1.reshape(5,2)
print(a2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

In [ ]:
#Iterate over a 1D array and print elements.
a1= np.array([1,2,3,4,5,6])
for i in a1:
  print(i)

1
2
3
4
5
6

In [ ]:
#Extract first row from a 2D array using slicing.
a1= np.array([[1,2,3],[4,5,6]])
print(a1[0,::])

[1 2 3]

In [ ]:
#Get elements from index 1 to 3 in a 1D array.
a1= np.array([1,2,3,4,5,6])
print(a1[1:4])

[2 3 4]

Pandas

In [ ]:
import pandas as pd
import numpy as np
a=[45,67,89]
arr= pd.Series(a)

In [ ]:
a= np.array([1,2,3,4,5,6,7])
b= np.array([4,5,6,7,8,9,10])
c=pd.Series(a,b)
print(c)

4     1
5     2
6     3
7     4
8     5
9     6
10    7
dtype: int64

In [ ]:
a= np.array([1,2,3,4,5,6,7])
b= np.array([4,5,6,7,8,9,10])
c=pd.Series(a+b)
print(c,'\n')
d=pd.Series(a+b)
print(d.to_string(index=False))  #to remove index column

0     5
1     7
2     9
3    11
4    13
5    15
6    17
dtype: int64

 5
 7
 9
11
13
15
17

In [ ]:
a= np.array([1,2,3,4,5,6,7])
b= np.array([4,5,6,7,8,9,10])
c= pd.Series(index= a,data=b)
print(c)

1     4
2     5
3     6
4     7
5     8
6     9
7    10
dtype: int64

Pandas DataFrame

In [ ]:
lst1= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
lst2= ['adam','eric','avril','max','esther','rob','Ava','Eve','Morgan','Jack','Rock','Ricky','Roxy','Ryan','Andrew']
df= pd.DataFrame(index=lst1,data=lst2)
df.columns=['name']
print('id')
print(df)

id
      name
1     adam
2     eric
3    avril
4      max
5   esther
6      rob
7      Ava
8      Eve
9   Morgan
10    Jack
11    Rock
12   Ricky
13    Roxy
14    Ryan
15  Andrew

In [ ]:
import pandas as pd
import numpy as np
print(df.head())
print('\n\n')
print(df.head(3))

     name
1    adam
2    eric
3   avril
4     max
5  esther



    name
1   adam
2   eric
3  avril

In [ ]:
print(df.tail())
print(df.tail(2))

      name
11    Rock
12   Ricky
13    Roxy
14    Ryan
15  Andrew
      name
14    Ryan
15  Andrew

# April 09,2026

In [ ]:
import pandas as pd
df=pd.read_csv("new_weather_data.csv")
df= df.drop('Unnamed: 0',axis=1)
print(df)

       Date Temperature(°c) Wind(km/hr) Weather_event Wind_direction
0       day     temperature   windspeed         event      Direction
1  1/1/2017              32           6          Rain             NE
2  1/2/2017              35           7         Sunny             SE
3  1/3/2017              28           2          Snow        No Wind
4  1/4/2017              24           7          Snow             NE
5  1/5/2017              32           4          Rain        No Wind
6  1/6/2017              31           2         Sunny             SE

In [ ]:
df= pd.read_csv("weather_data.csv")
print(df)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df= pd.read_csv("data.csv")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
#mean
df= pd.read_csv("data.csv")
arr= df['Calories'].mean()
print(arr)
df['Calories']= df['Calories'].fillna(arr)
print(df)
df.info()

375.79024390243904
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  169 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [ ]:
df= pd.read_csv("data.csv")
arr2= df['Calories'].median()
print(arr2)
df['Calories']= df['Calories'].fillna(arr2)
print(df)

318.6
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
df= pd.read_csv("data.csv")
arr3= df['Calories'].mode()[0]
print(arr3)
df['Calories']= df['Calories'].fillna(arr3)
print(df)

300.0
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
import pandas as pd
df= pd.read_csv("data_ashish.csv")
print(df.info)

<bound method DataFrame.info of      Duration  Pulse  Maxpulse  Calories       Date   Unnamed: 5  Unnamed: 6  \
0          60    110       130     409.1  01-01-2026         NaN         NaN
1          60    117       145     479.0  02-01-2026         NaN         NaN
2          60    103       135     340.0  03-01-2026         NaN         NaN
3          45    109       175     282.4  04-01-2026         NaN         NaN
4          45    117       148     406.0  05-01-2026         NaN         NaN
..        ...    ...       ...       ...         ...         ...         ...
164        60    105       140     290.8  14-06-2026         NaN         NaN
165        60    110       145     300.0  15-06-2026         NaN         NaN
166        60    115       145     310.2  16-06-2026         NaN         NaN
167        75    120       150     320.4  17-06-2026         NaN         NaN
168        75    125       150     330.4  18-06-2026         NaN         NaN

    Unnamed: 7 Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  \
0          NaN        NaN         NaN          NaN          NaN          NaN
1          NaN        NaN         NaN          NaN          NaN          NaN
2          NaN        NaN         NaN          NaN          NaN          NaN
3          NaN        NaN         NaN          NaN          NaN          NaN
4          NaN        NaN         NaN          NaN          NaN          NaN
..         ...        ...         ...          ...          ...          ...
164        NaN        NaN         NaN          NaN          NaN          NaN
165        NaN        NaN         NaN          NaN          NaN          NaN
166        NaN        NaN         NaN          NaN          NaN          NaN
167        NaN        NaN         NaN          NaN          NaN          NaN
168        NaN        NaN         NaN          NaN          NaN          NaN

     Unnamed: 13
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
..           ...
164          NaN
165          NaN
166          NaN
167          NaN
168          NaN

[169 rows x 14 columns]>

In [ ]:
'''Task 1: Removing Columns and Rows
Identify and remove unwanted or unnamed columns from the dataset.
Trim the dataset by deleting extra rows from the bottom so that only the first 150 rows remain.'''
import pandas as pd
df= pd.read_csv("data_ashish.csv")
df=df.copy()       #Have I used Copy here correctly or it needed to be placed somewhere else
df.columns = df.columns.str.strip()
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y', errors='coerce')

print(df)

print('\n\n\n Lets remove entire Unnamed Columns First:- \n')
df= df.loc[:, ~df.columns.str.contains('^Unnamed')]
print(df)

print('\n\n\nRemoving Extra Rows and keeping first 150 Rows:- \n')

df= df.head(150)

print(df)
#How can I check where my raw data is stored and where my copy data stored

     Duration  Pulse  Maxpulse  Calories       Date  Unnamed: 5  Unnamed: 6  \
0          60    110       130     409.1 2026-01-01         NaN         NaN
1          60    117       145     479.0 2026-01-02         NaN         NaN
2          60    103       135     340.0 2026-01-03         NaN         NaN
3          45    109       175     282.4 2026-01-04         NaN         NaN
4          45    117       148     406.0 2026-01-05         NaN         NaN
..        ...    ...       ...       ...        ...         ...         ...
164        60    105       140     290.8 2026-06-14         NaN         NaN
165        60    110       145     300.0 2026-06-15         NaN         NaN
166        60    115       145     310.2 2026-06-16         NaN         NaN
167        75    120       150     320.4 2026-06-17         NaN         NaN
168        75    125       150     330.4 2026-06-18         NaN         NaN

    Unnamed: 7 Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  \
0          NaN        NaN         NaN          NaN          NaN          NaN
1          NaN        NaN         NaN          NaN          NaN          NaN
2          NaN        NaN         NaN          NaN          NaN          NaN
3          NaN        NaN         NaN          NaN          NaN          NaN
4          NaN        NaN         NaN          NaN          NaN          NaN
..         ...        ...         ...          ...          ...          ...
164        NaN        NaN         NaN          NaN          NaN          NaN
165        NaN        NaN         NaN          NaN          NaN          NaN
166        NaN        NaN         NaN          NaN          NaN          NaN
167        NaN        NaN         NaN          NaN          NaN          NaN
168        NaN        NaN         NaN          NaN          NaN          NaN

     Unnamed: 13
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
..           ...
164          NaN
165          NaN
166          NaN
167          NaN
168          NaN

[169 rows x 14 columns]



 Lets remove entire Unnamed Columns First:-

     Duration  Pulse  Maxpulse  Calories       Date
0          60    110       130     409.1 2026-01-01
1          60    117       145     479.0 2026-01-02
2          60    103       135     340.0 2026-01-03
3          45    109       175     282.4 2026-01-04
4          45    117       148     406.0 2026-01-05
..        ...    ...       ...       ...        ...
164        60    105       140     290.8 2026-06-14
165        60    110       145     300.0 2026-06-15
166        60    115       145     310.2 2026-06-16
167        75    120       150     320.4 2026-06-17
168        75    125       150     330.4 2026-06-18

[169 rows x 5 columns]



Removing Extra Rows and keeping first 150 Rows:-

     Duration  Pulse  Maxpulse  Calories       Date
0          60    110       130     409.1 2026-01-01
1          60    117       145     479.0 2026-01-02
2          60    103       135     340.0 2026-01-03
3          45    109       175     282.4 2026-01-04
4          45    117       148     406.0 2026-01-05
..        ...    ...       ...       ...        ...
145        45    106       126     270.8 2026-05-26
146        60    107       136     400.0 2026-05-27
147        60    112       146     361.9 2026-05-28
148        30    103       127     185.0 2026-05-29
149        60    110       150     409.4 2026-05-30

[150 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  150 non-null    int64
 1   Pulse     150 non-null    int64
 2   Maxpulse  150 non-null    int64
 3   Calories  145 non-null    float64
 4   Date      60 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 6.0 KB

In [ ]:
"""Task 2: Handling Missing Values
Identify columns with null (missing) values.
Replace missing values using:
Mean (average of values)
Median (middle value)
Mode (most frequent value)"""


arr= df['Calories'].mean()
print('Mean:- ',arr)
df['Calories']= df['Calories'].fillna(arr)
print(df)

Mean:-  384.89034482758626
     Duration  Pulse  Maxpulse  Calories       Date
0          60    110       130     409.1 2026-01-01
1          60    117       145     479.0 2026-01-02
2          60    103       135     340.0 2026-01-03
3          45    109       175     282.4 2026-01-04
4          45    117       148     406.0 2026-01-05
..        ...    ...       ...       ...        ...
145        45    106       126     270.8 2026-05-26
146        60    107       136     400.0 2026-05-27
147        60    112       146     361.9 2026-05-28
148        30    103       127     185.0 2026-05-29
149        60    110       150     409.4 2026-05-30

[150 rows x 5 columns]

In [ ]:
arr2= df['Calories'].median()
print('Median:- ',arr2)
df['Calories']= df['Calories'].fillna(arr2)
print(df)

Median:-  326.35
     Duration  Pulse  Maxpulse  Calories       Date
0          60    110       130     409.1 2026-01-01
1          60    117       145     479.0 2026-01-02
2          60    103       135     340.0 2026-01-03
3          45    109       175     282.4 2026-01-04
4          45    117       148     406.0 2026-01-05
..        ...    ...       ...       ...        ...
145        45    106       126     270.8 2026-05-26
146        60    107       136     400.0 2026-05-27
147        60    112       146     361.9 2026-05-28
148        30    103       127     185.0 2026-05-29
149        60    110       150     409.4 2026-05-30

[150 rows x 5 columns]

In [ ]:
arr3= df['Calories'].mode()[0]
print('Mode:- ',arr3)
df['Calories']= df['Calories'].fillna(arr3)
print(df)

Mode:-  300.0
     Duration  Pulse  Maxpulse  Calories       Date
0          60    110       130     409.1 2026-01-01
1          60    117       145     479.0 2026-01-02
2          60    103       135     340.0 2026-01-03
3          45    109       175     282.4 2026-01-04
4          45    117       148     406.0 2026-01-05
..        ...    ...       ...       ...        ...
145        45    106       126     270.8 2026-05-26
146        60    107       136     400.0 2026-05-27
147        60    112       146     361.9 2026-05-28
148        30    103       127     185.0 2026-05-29
149        60    110       150     409.4 2026-05-30

[150 rows x 5 columns]

# Regression Classification:
>Duration, Pulse, Maxpulse, Calories

I will use Randomforest for this as there are only 150 rows. I will compare it to linear regression to check the baseline. I will also compare this with XGBoost and LightGBM.

In [ ]:
import pandas as pd
df= pd.read_csv("HouseListings-Top45Cities-10292023-kaggle.csv", encoding='latin1')
df.head

,City,Price,Address,Number_Beds,Number_Baths,Province,Population,Latitude,Longitude,Median_Family_Income
0,Toronto,779900.0,#318 -20 SOUTHPORT ST,3,2,Ontario,5647656,43.7417,-79.3733,97000.0
1,Toronto,799999.0,#818 -60 SOUTHPORT ST,3,1,Ontario,5647656,43.7417,-79.3733,97000.0
2,Toronto,799900.0,#714 -859 THE QUEENSWAY,2,2,Ontario,5647656,43.7417,-79.3733,97000.0
3,Toronto,1200000.0,275 MORTIMER AVE,4,2,Ontario,5647656,43.7417,-79.3733,97000.0
4,Toronto,668800.0,#420 -388 RICHMOND ST,1,1,Ontario,5647656,43.7417,-79.3733,97000.0

In [ ]:
#Check for missing values
df.isna().sum()

City                    0
Price                   0
Address                 0
Number_Beds             0
Number_Baths            0
Province                0
Population              0
Latitude                0
Longitude               0
Median_Family_Income    0
dtype: int64

# Categorical Classification:

>City, Address, Province

# Regression Classification:
>Price, Number_Beds, Number_Baths, Population
>Latitude, Longitude, Median_Family_Income

Linear Regression model as it is good for simple numeric relationship, fast and can be used to compare the baseline.

1. Random Forest Regressor: as accuracy is high for small dataset. good for non linear pattern.

2. XGBoost Regressor:- accuracy is high in complex data. not so ideal for small size data base.

3. LightGBM:- fastest and works good with numeric data.

In my opinion, I will use all 3 models and avg their RMSE/MAE. This will give me stable and better accuracy.